### ISSUE TITLE
Files Uploaded with CDB filesync are inaccess to elastic search

### ISSUE THREAD

**Issue by andyryan** [ibm-cloud-docs/databases-for-elasticsearch#2]
I have followed the documentation to attempt to upload a file containing synonyms for use in an elastic search filter, however when I try to create the filter I am met with the following error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "access_control_exception",
        "reason": "access denied (\"java.io.FilePermission\" \"/data/ibm_file_sync/current/Ontology.txt\" \"read\")"
      }
    ],
    "type": "access_control_exception",
    "reason": "access denied (\"java.io.FilePermission\" \"/data/ibm_file_sync/current/Ontology.txt\" \"read\")"
  },
  "status": 500
}
```
This is due to the default security settings in Elasticsearch only providing access to files under Elasticsearch's `conf` folder as noted here: https://github.com/elastic/elasticsearch/issues/16995 and https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-synonym-tokenfilter.html

I cannot find any method to configure elastic search to have access to the filesync folder, or have filesync write to the conf folder

**Comment by acdntlpoet** [comment]
@andyryan  This doesn't appear to be a docs issue, but rather a potential bug or other configuration issue. We do set the permissions to access that location, so are wondering what may be causing this error. To further investigate, please open a [support ticket](https://cloud.ibm.com/unifiedsupport/cases/add) with details including the formation crn so we can look at it directly and identify any bug that may need development intervention.
